SocialMusic/SocialMusic/Models/Album.cs
namespace SocialMusic.Models
{
    public class Album
    {
        public string Name { get; set; }
        public string Artist { get; set; }
    }
}

SocialMusic/SocialMusic/Models/Artist.cs
namespace SocialMusic.Models
{
    public class Artist
    {
        public string Name { get; set; }
    }
}

SocialMusic/SocialMusic/Models/ArtistAlbumViewModel.cs
using System.Collections.Generic;

namespace SocialMusic.Models
{
    public class ArtistAlbumViewModel
    {
        public List<Album> Albums { get; set; }
        public List<Artist> Artists { get; set; }
    }
}

SocialMusic/SocialMusic/Models/SocialMusicDbContext.cs
using SocialMusic.Models;
using System.Data.Entity;

namespace SocialMusic.DBContexts
{
    public class SocialMusicDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<WallMessage> WallMessages { get; set; }
    }
}

SocialMusic/SocialMusic/Models/User.cs
using System;

namespace SocialMusic.Models
{
    public class User
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string LastFmUsername { get; set; }
        public DateTime Created { get; set; }
    }   
}

SocialMusic/SocialMusic/Models/WallMessage.cs
using System;

namespace SocialMusic.Models
{
    public class WallMessage
    {
        public int ID { get; set; }
        public DateTime Created { get; set; }
        public string Message { get; set; }
    }
}

SocialMusic/SocialMusic/Controllers/AlbumController.cs
using SocialMusic.Handlers;
using SocialMusic.Models;
using System.Web.Mvc;

namespace SocialMusic.Controllers
{
    public class AlbumController : Controller
    {
        [ChildActionOnly]
        public ActionResult TopAlbumsAndArtists()
        {
            AuthentificationHandler authHandler = new AuthentificationHandler(Session);
            ArtistAlbumViewModel AAVM = new ArtistAlbumViewModel();
            LastFmApiHandler lastFmApiHandler = new LastFmApiHandler();

            AAVM.Albums = lastFmApiHandler.GetAlbum(authHandler.GetUser().LastFmUsername);
            AAVM.Artists = lastFmApiHandler.GetArtist(authHandler.GetUser().LastFmUsername);
                     
            return PartialView("/Views/Partials/_TopAlbumsAndArtists.cshtml", AAVM);        
        }
    }
}

SocialMusic/SocialMusic/Controllers/HomeController.cs
using SocialMusic.DBContexts;
using SocialMusic.Handlers;
using SocialMusic.Models;
using System;
using System.Web.Mvc;

namespace SocialMusic.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string username, string password)
        {
            
            var authentificationHandler = new AuthentificationHandler(Session);

            User tempUser = new User();
            tempUser.Username = username;
            tempUser.Password = password;

            if (authentificationHandler.LogIn(tempUser))
            {
                return JavaScript("window.location = '/Profile/Index'");
            }

            return this.Json(new { success = false, message = "loginerror" });
        }

        [HttpPost]
        public ActionResult LogOut(User user)
        {
            var authentificationHandler = new AuthentificationHandler(Session);
            authentificationHandler.LogOut();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(User user)
        {
            var authentificationHandler = new AuthentificationHandler(Session);
            using (var db = new SocialMusicDbContext())
            {
                user.Created = DateTime.Now;              
                user.Password = authentificationHandler.HashPassword(user.Password);
                
                db.Users.Add(user);
                db.SaveChanges();
            }

            return Redirect("Index");
        }
    }
}

SocialMusic/SocialMusic/Controllers/ProfileController.cs
using SocialMusic.Attributes;
using System.Web.Mvc;

namespace SocialMusic.Controllers
{
    public class ProfileController : Controller
    {
        [Authenticate(View = "NotAuthenticated")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

SocialMusic/SocialMusic/Controllers/PublicProfileController.cs
using SocialMusic.DBContexts;
using SocialMusic.Handlers;
using SocialMusic.Models;
using System.Linq;
using System.Web.Mvc;

namespace SocialMusic.Controllers
{
    public class PublicProfileController : Controller
    {
        /// <summary>
        /// Returns the public profile of matching profile name
        /// </summary>
        public ActionResult Index(object name)
        {
            User user = new User();
            using (var db = new SocialMusicDbContext())
            {
                user = db.Users.FirstOrDefault(s => s.Username == (string)name);
            }
            if (user == null)
            {
                return RedirectToAction("Index", "Users");
            }

            return View(user);
        }

        [ChildActionOnly]
        public ActionResult TopAlbumsAndArtists(object name)
        {
            ArtistAlbumViewModel AAVM = new ArtistAlbumViewModel();
            LastFmApiHandler lastFmApiHandler = new LastFmApiHandler();
            User user = new User();
            using (var db = new SocialMusicDbContext())
            {
                user = db.Users.FirstOrDefault(s => s.Username == (string)name);
            }

            AAVM.Albums = lastFmApiHandler.GetAlbum(user.LastFmUsername);
            AAVM.Artists = lastFmApiHandler.GetArtist(user.LastFmUsername);

            return PartialView("/Views/Partials/_TopAlbumsAndArtists.cshtml", AAVM);
        }

    }
}

SocialMusic/SocialMusic/Controllers/UsersController.cs
using SocialMusic.DBContexts;
using SocialMusic.Models;
using System.Linq;
using System.Web.Mvc;

namespace SocialMusic.Controllers
{
    public class UsersController : Controller
    {
        public ActionResult Index()
        {
            User[] users;
            using (var db = new SocialMusicDbContext())
            {
                users = db.Users.Take(100).ToArray();
            }

            return View(users);
        }
    }
}

SocialMusic/SocialMusic/Controllers/WallMessagesController.cs
using SocialMusic.DBContexts;
using SocialMusic.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace SocialMusic.Controllers
{
    public class WallMessagesController : Controller
    {
        [ChildActionOnly]
        public ActionResult Messages()
        {
            WallMessage[] messages;
            using (var db = new SocialMusicDbContext())
            {
                messages = db.WallMessages.Take(100).ToArray();
            }

            return PartialView("/Views/Partials/_Messages.cshtml", messages);
        }


        [HttpGet]
        public ActionResult PostToWall()
        {
            return View();
        }
        
        [HttpPost]
        public void PostToWall(string message)
        {            
            WallMessage m = new WallMessage();
            using (var db = new SocialMusicDbContext())
            {
                m.Created = DateTime.Now;
                m.Message = message;

                db.WallMessages.Add(m);

                db.SaveChanges();
            }
        }
        
    }
}

SocialMusic/SocialMusic/Views/Home/Index.cshtml
@model SocialMusic.Models.User

<div class="logInBox">

    <p class="siteLogo">Social<strong>Music</strong></p>
    <br />
    <form id="message">
        <input type="text" id="usernameInput" />
        <br />
        <input type="password" id="passwordInput" />
        <br />
        <button type="submit" class="logInButton">Login</button>
    </form>
    <h1 id="errorMessage"></h1>
    <h3>Not a member? @Html.ActionLink("Register", "Register") </h3>
    <h3>@Html.ActionLink("Users", "Index", "Users") </h3>


</div>


<script>
    
    $('#message').submit(function (e) {
        /*Prevents the page to reaload like it normaly should*/
        e.preventDefault()
        /*Do the post through Ajax*/
        $.ajax({
            type: 'POST',
            url: '/Home/LogIn',
            data: {
                username: $('#usernameInput').val(),
                password: $('#passwordInput').val()
            },
            success: function (data){
                if (!data.success && data.message == "loginerror") {
                    $('#errorMessage').text("Wrong Username or Password")
                }
            }
        })
        /*Sets the text input to empty*/
        $('#passwordInput').val('')
    })
</script>

SocialMusic/SocialMusic/Views/Home/Register.cshtml
@model SocialMusic.Models.User

<div class="logInBox">
    @using (Html.BeginForm())
    {
        <p class="siteLogo">Social<strong>Music</strong></p>
        <br />
        @Html.EditorFor(s => s.Username, new { htmlAttributes = new { placeholder = "Username" } });
        <br />
        @Html.EditorFor(s => s.LastFmUsername, new { htmlAttributes = new { placeholder = "LasFM Name" } });
        <br />
        @Html.PasswordFor(s => s.Password, new { @class = "form-control", placeholder = "Password" });
        <br />
        <button type="submit" class="logInButton">Register</button>
    }
</div>

SocialMusic/SocialMusic/Views/Partials/_Messages.cshtml
<div class="wallBox">
    <p class="siteLogo">W<strong>all</strong></p>
    <div class="scrollDiv">
        <ul class="wallList" id="newMessages"></ul>
        <ul class="wallList" id="wallList">
            @for (int i = Model.Length - 1; i > 0; i--)
            {
                <li>@Model[i].Message</li>
            }
        </ul>
    </div>
    <form id="message">
        <input type="text" id="input" />
        <br />
        <button type="submit" id="postButton" class="logInButton">Post</button>
    </form>
</div>

SocialMusic/SocialMusic/Views/Partials/_SearchAlbum.cshtml
<div>
    <h3>Search Album</h3>
    <form id="searchForm">
        <input name="name" type="text" id="albumName" size="5" />
        <input type="submit" value="submit" />
    </form>
    <p id="album" />
    <ul id="albumList" />
</div>

SocialMusic/SocialMusic/Views/Partials/_TopAlbumsAndArtists.cshtml
@model SocialMusic.Models.ArtistAlbumViewModel

<div>

    <ul>
        @foreach (var album in Model.Albums)
        {
            <li>@album.Name - @album.Artist</li>
        }
    </ul>
    <ul>
        @foreach (var artist in Model.Artists)
        {
            <li>@artist.Name</li>
        }
    </ul>
</div>

SocialMusic/SocialMusic/Views/PublicProfile/Index.cshtml
@model SocialMusic.Models.User

<h1 class="profileHeader">This is @Model.Username's profile</h1>
<br />
<h3>Post something on @Model.Username's wall!</h3>
<br/>
<h3>@Model.Username's name on last FM is @Model.LastFmUsername</h3>
<h3>@Model.Username's Top 5 Albums and artists</h3>
@{Html.RenderAction("TopAlbumsAndArtists");}
@{ Html.RenderAction("Messages", "WallMessages");}

SocialMusic/SocialMusic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Main.css" rel="stylesheet" type="text/css" />
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Gruppo" rel="stylesheet">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <ul class="top-nav-list">
        <li>Home</li>
        <li>Home</li>
        <li>Home</li>
        <li>Home</li>
    </ul>


    <div class="container body-content">
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/SocialMusic/main.js"></script>
    <script src="~/scripts/SocialMusic/albumsearch.js"></script>
    <script src="~/scripts/SocialMusic/wallmessage.js"></script>
</body>
</html>

SocialMusic/SocialMusic/Views/Users/Index.cshtml
@model SocialMusic.Models.User[]

<h2>Users</h2>

<ul>
    @foreach (var user in Model)
    {       
        <li>@Html.ActionLink(user.Username, "Index", "PublicProfile/" + user.Username) </li>
    }
</ul>